### ISSUE TITLE
Flask?

### ISSUE THREAD

**Issue by Quadsam** [JohnathanLP/cmcppgroups#1]
Do you know anything about flask? If so can you help me?

I keep getting the error
Traceback (most recent call last):
  File "./run.py", line 2, in <module>
    from app import app
  File "/home/Samuel/Documents/Website/app/__init__.py", line 4, in <module>
    from app import views
  File "/home/Samuel/Documents/Website/app/views.py", line 15
    'body': 'The Avengers movie was so cool!'
^
SyntaxError: invalid syntax

The arrow is pointing to the last ' symbol in body like this 'body'< except the arrow was underneath
The file attached is the views.py the error is in
I converted it to a .txt because i cant attach a .py file

[views.txt](https://github.com/JohnathanLP/cmcppgroups/files/1448400/views.txt)

**Comment by JohnathanLP** [comment]
I haven't used flask at all myself. I could maybe look at it in a week or two, but this week is very full for me.

**Comment by Quadsam** [comment]
Ok thanks

**Comment by Quadsam** [comment]
Ok I found it out just had to follow the tutorial a little farther

**Comment by Quadsam** [comment]
Also do you know of a website where I can easily learn Java?

**Comment by JohnathanLP** [comment]
Codecademy has some pretty good tutorials.
